#!/usr/bin/env bash
sxhkd &                                         # enable keybinds
wal -R &                                        # set wallpaper & theme
# start-pulseaudio-x11 &                        # make audio work
compton                                         # start compositor
redshift -l 53:0 &                              # make our eyes less strained
# . "$HOME/.config/lemonbar/bar.sh" &           # useful system info
# . "$HOME/.config/dunst/launch.sh" &           # useful notifications
