#! /bin/sh

export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

# . "${HOME}/.cache/wal/colors.sh"

bspc monitor --reset-desktops 1 2 3 4 5 6 7 8 9 0

bspc config border_width		2 

bspc config split_ratio			0.5
bspc config borderless_monocle		true
bspc config gapless_monocle		true

bspc rule -a Nightly state=tiled
bspc rule -a Nightly:Dialog state=floating
bspc rule -a Nightly:Prompt state=floating

# bspc rule -a URxvt:scratch state=floating rectangle=800x600+560+300 sticky=on

# generic rules
bspc rule -a Dialog state=floating
bspc rule -a Prompt state=floating

bspc config focused_border_color		"$color2"
bspc config active_border_color			"$color1"
bspc config normal_border_color			"$color1"

if [ "$1" = "reload" ]; then
	echo "reloaded config."
else
	"$BSPWM_CONFIG/autostart" &
	# "$HOME/.scripts/toggle-gaps.sh" gaps &
fi

. "$HOME/.config/lemonbar/bar.sh"
